name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi \
          git \
          curl \
          zip \
          bison \
          flex \
          libssl-dev \
          bc \
          clang \
          lld \
          libncurses-dev \
          libelf-dev \
          libncurses5-dev \
          ccache \
          rsync \
          unzip \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-dev \
          lzop \
          libstdc++6 \
          libxml2-utils \
          device-tree-compiler \
          pkg-config \
          genext2fs \
          liblz4-tool \
          cmake \
          ninja-build \
          automake \
          autoconf \
          texinfo \
          gettext \
          gawk \
          fakeroot \
          libfile-fcntllock-perl \
          socat

    - name: Build Kernel
      run: |
        # Execute chmod and the script within the checked-out repository
        cd ${{ github.workspace }}
        chmod +x b.sh
        ./b.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: AnyKernel/sphinXkernel-fern!-rosemary-v1.0-svendor.zip
